workflows:
  android-workflow:
    name: Android Build (Auto Locate)
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Locate project and build
        script: |
          echo "Searching for pubspec.yaml ..."
          APP_DIR=$(dirname "$(find . -name pubspec.yaml | head -n 1)")
          echo "Project found at: $APP_DIR"
          cd "$APP_DIR"
          flutter pub get
          flutter build apk
    artifacts:
      - "**/build/app/outputs/flutter-apk/app-release.apk"
