workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - cd provider_counter
      - flutter pub get
      - flutter build apk
    artifacts:
      - provider_counter/build/app/outputs/flutter-apk/app-release.apk
